%% analyze_servo_prps_amplitude_sweep.m
% Servo amplitude-bandwidth sweep: map achievable vectoring bandwidth
% f_vec(theta_amp) across a ladder of angle amplitudes, then invert the
% feasibility thrust trade to the minimum thrust that stays in spec.
%
% Campaign (firmware servo_prps_log.orchestrate.json, generated by
% tools/design_servo_prps_excitation.py --amplitude-ladder):
%   Each angle-amplitude RUNG (run_name "ladder_aNN_...") carries:
%     - a linear PRPS block ("ladder_aNN_lin_rKK"): several crest-min
%       realizations, top frequency capped at min(0.9*f_slew(theta), coherence
%       ceiling), so the response stays linear -> FOPD (K,tau,L)(theta), corner
%       f_c(theta) = 1/(2*pi*tau).
%     - slew probes ("ladder_aNN_probe_fX") on the large rungs whose slew knee
%       sits inside the trusted band: single tones bracketing and pushing a bit
%       past f_slew(theta). Describing-function gain droop + THD locate the
%       measured slew knee f_slew(theta).
%
% Effective vectoring bandwidth per rung:
%   f_vec(theta) = min( f_c(theta) , f_slew(theta) )
% corner-limited (flat) at small amplitude, slew-limited (~1/theta) at large.
%
% Feasibility inversion (analysis/feasibility/analyze_thrust_angle_bandwidth_trade.m
% writes data/processed/feasibility/thrust_angle_bandwidth_trade.csv):
%   The campaign supplies the measured f_vec(theta) that is compared against
%   the true M3 disturbance-rejection crossover and the purchase-facing 10 Hz
%   vectoring-bandwidth target in docs/feasibility.md and docs/hardware_selection.md.
%
% Empirical transfer function: G(jw) = theta_rad(jw) / command_delta_us(jw) [rad/us]

clearvars -except DATASET_STATUS SAVE_FIGURES;
clc; close all;

%% User options

if ~exist("SAVE_FIGURES", "var"), SAVE_FIGURES = true; end
if ~exist("DATASET_STATUS", "var")
    DATASET_STATUS = "candidate";
else
    DATASET_STATUS = string(DATASET_STATUS);
end

LADDER_PREFIX = "ladder_";      % run_name prefix that selects this campaign
LIN_TOKEN     = "_lin";
PROBE_TOKEN   = "_probe";

% Measured upgraded-servo context (2026-06-29 step test; used only for the
% slew-knee formula on UN-probed rungs and for annotation).
SLEW_EST_DEG_S = 900.0;
CORNER_EST_HZ  = 9.0;
COH_CEILING_HZ = 15.0;
M3_REQUIRED_CROSSOVER_HZ = sqrt(1.0 / (0.45 * 0.015)) / (2*pi);
PURCHASE_TARGET_BW_HZ = 10.0;

% Knee-detection thresholds on the probe tones.
GAIN_DROOP_DB = 3.0;    % gain this far below the rung's linear low-freq gain
THD_THRESH    = 0.10;   % or angle THD at/above this
N_HARMONICS   = 5;      % harmonics summed for THD

MIN_COHERENCE_FOR_FIT = 0.60;

%% FRF / fit options (mirror analyze_servo_prps_two_band.m; band widened to the
%  coherence ceiling so small-rung linear blocks resolve the ~9 Hz corner).

COUNTS_PER_REV          = encoderAngleScale().counts_per_rev;
DEFAULT_SERVO_CENTER_US = 1428;   % campaign center (firmware truth)
SERVO_OUTPUT_SIGN       = -1;     % command_delta_us up -> theta down
DEFAULT_FREQ_LABEL      = "ladder";

FRF_OPTS = struct();
FRF_OPTS.inferFreqsFromInput       = true;
FRF_OPTS.freqListHz                = [];
FRF_OPTS.inputBinRelativeThreshold = 0.05;
FRF_OPTS.freqMinHz                 = 0.2;
FRF_OPTS.freqMaxHz                 = COH_CEILING_HZ + 0.5;
FRF_OPTS.removePeriodMean          = true;
FRF_OPTS.detrendEachPeriod         = false;
FRF_OPTS.minPeriodsPerRun          = 2;
FRF_OPTS.minSamplesPerPeriod       = 20;
FRF_OPTS.useNominalCommandDtForFrf = true;
FRF_OPTS.nominalCommandDtS         = 0.005;

FIT_OPTS = struct();
FIT_OPTS.weightingMode             = "relative_with_coh";
FIT_OPTS.gainFloorMode             = "fraction_of_median";
FIT_OPTS.gainFloorFractionOfMedian = 0.20;
FIT_OPTS.manualGainFloor           = 1e-5;
FIT_OPTS.initialK                  = pi / 2000;
FIT_OPTS.initialTau                = 0.018;
FIT_OPTS.initialDelay              = 0.030;
FIT_OPTS.initialTau2               = 0.02;
FIT_OPTS.minTau                    = 0.003;
FIT_OPTS.maxTau                    = 2.0;
FIT_OPTS.minDelay                  = 0.0;
FIT_OPTS.maxDelay                  = 0.50;
FIT_OPTS.minGainAbs                = 1e-5;
FIT_OPTS.maxGainAbs                = 0.01;
FIT_OPTS.maxIter                   = 5000;
FIT_OPTS.maxEval                   = 10000;

%% Locate data / output folders

scriptPath = mfilename("fullpath");
repoRoot   = findRepoRoot(scriptPath);
addpath(fullfile(repoRoot, "analysis", "utils"));

dataDir = getMirroredRawDataDir(scriptPath, DATASET_STATUS);
plotDir = getMirroredPlotDir(scriptPath);
relativeAnalysisDir = getRelativeAnalysisDir(scriptPath);
reportDir = fullfile(repoRoot, "reports", relativeAnalysisDir);
processedDir = fullfile(repoRoot, "data", "processed", relativeAnalysisDir);

if ~isfolder(reportDir), mkdir(reportDir); end
if ~isfolder(processedDir), mkdir(processedDir); end

if ~isfolder(dataDir)
    error("Data folder not found:\n%s", dataDir);
end

csvFiles = dir(fullfile(dataDir, "*.csv"));
if isempty(csvFiles)
    error("No CSV files in:\n%s\nRun the amplitude-ladder campaign first.", dataDir);
end
[~, sortIdx] = sort(string({csvFiles.name}));
csvFiles = csvFiles(sortIdx);

fprintf("\nServo PRPS amplitude-bandwidth sweep\n");
fprintf("  Dataset: %s\n", dataDir);
fprintf("  CSV files: %d\n", numel(csvFiles));

%% Load, normalize, keep only ladder PRPS-segment rows

Tall = ServoPrpsId.readCombinedCsvTables(csvFiles);
Tall = ServoPrpsId.normalizeServoPrpsTable( ...
    Tall, COUNTS_PER_REV, DEFAULT_SERVO_CENTER_US, DEFAULT_FREQ_LABEL, SERVO_OUTPUT_SIGN);

Tall = Tall(strcmpi(string(Tall.segment), "prps"), :);
isLadder = startsWith(string(Tall.run_name), LADDER_PREFIX);
Tall = Tall(isLadder, :);
if isempty(Tall)
    error("No ""%s*"" PRPS rows found. Is this the amplitude-ladder campaign?", LADDER_PREFIX);
end

runNames = unique(string(Tall.run_name), "stable");
rungTags = ladderTagOf(runNames);                 % "a08" etc
uniqueTags = unique(rungTags, "stable");
thetaDeg  = arrayfun(@(t) str2double(extractAfter(t, "a")), uniqueTags);
[thetaDeg, order] = sort(thetaDeg);
uniqueTags = uniqueTags(order);
nRung = numel(uniqueTags);

fprintf("  Rungs: %d  (%s deg)\n", nRung, strjoin(string(thetaDeg(:).'), ", "));

%% Per-rung analysis

rungTemplate = struct("theta_deg", NaN, "tag", "", "amp_us", NaN, ...
    "K", NaN, "tau_s", NaN, "delay_s", NaN, "fc_hz", NaN, "linGainDc", NaN, ...
    "nLinLines", NaN, "cohEdgeHz", NaN, ...
    "probe_f", [], "probe_gain", [], "probe_droopDb", [], "probe_thd", [], ...
    "knee_hz", NaN, "knee_source", "", "f_vec_hz", NaN);
rung = repmat(rungTemplate, nRung, 1);

for i = 1:nRung
    tag = uniqueTags(i);
    theta = thetaDeg(i);

    isThis = rungTags == tag;
    thisRuns = runNames(isThis);
    linRuns   = thisRuns(contains(thisRuns, LIN_TOKEN));
    probeRuns = thisRuns(contains(thisRuns, PROBE_TOKEN));

    r = struct();
    r.theta_deg = theta;
    r.tag = tag;

    % ---- linear block -> FOPD ----
    Dlin = ServoPrpsId.cleanServoPrpsTable( ...
        Tall(ismember(string(Tall.run_name), linRuns), :));
    r.amp_us = max(abs(ServoPrpsId.forceNumeric(Dlin.command_delta_us)), [], "omitnan");

    frf = ServoPrpsId.estimatePrpsFrfFromTable(Dlin, "lin_" + tag, "lin", FRF_OPTS);
    fitMask = frf.coherence >= MIN_COHERENCE_FOR_FIT & isfinite(frf.G_emp);
    if nnz(fitMask) < 2
        warning("Rung %s: <2 coherent linear FRF points; skipping FOPD.", tag);
        r.K = NaN; r.tau_s = NaN; r.delay_s = NaN; r.fc_hz = NaN; r.linGainDc = NaN;
        r.nLinLines = nnz(fitMask); r.cohEdgeHz = NaN;
    else
        m = ServoPrpsId.fitOneFrequencyModel("first_order_delay", ...
            frf.f_Hz(fitMask), frf.G_emp(fitMask), frf.coherence(fitMask), FIT_OPTS);
        r.K = m.K; r.tau_s = m.tau1_s; r.delay_s = m.delay_s;
        r.fc_hz = 1 / (2*pi*m.tau1_s);
        r.linGainDc = abs(m.K);           % low-frequency gain reference (rad/us)
        r.nLinLines = nnz(fitMask);
        r.cohEdgeHz = contiguousCoherenceEdge(frf, MIN_COHERENCE_FOR_FIT);
    end

    % ---- slew probes -> describing-function gain droop + THD ----
    nProbeRuns = numel(probeRuns);
    pf = nan(nProbeRuns, 1); pg = nan(nProbeRuns, 1);
    pd = nan(nProbeRuns, 1); pt = nan(nProbeRuns, 1);
    nProbeMeas = 0;
    for j = 1:numel(probeRuns)
        Dp = ServoPrpsId.cleanServoPrpsTable( ...
            Tall(string(Tall.run_name) == probeRuns(j), :));
        meas = measureProbeTone(Dp, FRF_OPTS.nominalCommandDtS, N_HARMONICS);
        if isempty(meas) || ~isfinite(meas.gain_abs)
            continue;
        end
        nProbeMeas = nProbeMeas + 1;
        pf(nProbeMeas) = meas.f_hz;
        pg(nProbeMeas) = meas.gain_abs;
        pt(nProbeMeas) = meas.thd;
        refGain = r.linGainDc;
        if ~isfinite(refGain) || refGain <= 0, refGain = meas.gain_abs; end
        pd(nProbeMeas) = 20*log10(meas.gain_abs / refGain);
    end
    pf = pf(1:nProbeMeas); pg = pg(1:nProbeMeas);
    pd = pd(1:nProbeMeas); pt = pt(1:nProbeMeas);
    [pf, si] = sort(pf); pg = pg(si); pd = pd(si); pt = pt(si);
    r.probe_f = pf; r.probe_gain = pg; r.probe_droopDb = pd; r.probe_thd = pt;

    % ---- knee ----
    if isempty(pf)
        r.knee_hz = SLEW_EST_DEG_S / (2*pi*theta);   % formula (knee above band)
        r.knee_source = "slew-formula (unprobed)";
    else
        [kneeHz, src] = findKnee(pf, pd, pt, GAIN_DROOP_DB, THD_THRESH);
        r.knee_hz = kneeHz; r.knee_source = src;
    end

    % ---- effective vectoring bandwidth ----
    r.f_vec_hz = min([r.fc_hz, r.knee_hz], [], "omitnan");

    rung(i) = r;

    fprintf("  %-4s theta=%2.0f deg | K=%.4g tau=%.1f ms fc=%.2f Hz | knee=%.2f Hz (%s) | f_vec=%.2f Hz\n", ...
        tag, theta, r.K, r.tau_s*1e3, r.fc_hz, r.knee_hz, r.knee_source, r.f_vec_hz);
end

thetaArr = [rung.theta_deg].';
fcArr    = [rung.fc_hz].';
kneeArr  = [rung.knee_hz].';
fvecArr  = [rung.f_vec_hz].';

summaryTable = table( ...
    thetaArr, ...
    [rung.amp_us].', ...
    [rung.K].', ...
    [rung.tau_s].', ...
    [rung.delay_s].', ...
    fcArr, ...
    [rung.nLinLines].', ...
    [rung.cohEdgeHz].', ...
    kneeArr, ...
    string({rung.knee_source}).', ...
    fvecArr, ...
    'VariableNames', { ...
        'theta_amp_deg', ...
        'amplitude_us', ...
        'K_rad_per_us', ...
        'tau_s', ...
        'delay_s', ...
        'linear_corner_Hz', ...
        'num_coherent_linear_lines', ...
        'coherence_edge_Hz', ...
        'slew_knee_Hz', ...
        'knee_source', ...
        'f_vec_Hz'});
summaryTable.M3_crossover_pass = summaryTable.f_vec_Hz >= M3_REQUIRED_CROSSOVER_HZ;
summaryTable.purchase_target_pass = summaryTable.f_vec_Hz >= PURCHASE_TARGET_BW_HZ;

probeTable = table();
for i = 1:numel(rung)
    if isempty(rung(i).probe_f), continue; end
    Ti = table( ...
        repmat(rung(i).theta_deg, numel(rung(i).probe_f), 1), ...
        rung(i).probe_f(:), ...
        rung(i).probe_gain(:), ...
        rung(i).probe_droopDb(:), ...
        rung(i).probe_thd(:), ...
        'VariableNames', {'theta_amp_deg', 'probe_frequency_Hz', ...
            'gain_abs_rad_per_us', 'gain_droop_dB', 'angle_THD'});
    probeTable = [probeTable; Ti]; %#ok<AGROW>
end

%% Requirement checks

req = struct();
req.m3CrossoverHz = M3_REQUIRED_CROSSOVER_HZ;
req.purchaseTargetHz = PURCHASE_TARGET_BW_HZ;
req.minMeasuredFvecHz = min(fvecArr, [], "omitnan");
req.maxMeasuredFvecHz = max(fvecArr, [], "omitnan");
finiteFvec = isfinite(fvecArr);
req.allM3Pass = any(finiteFvec) && all(fvecArr(finiteFvec) >= M3_REQUIRED_CROSSOVER_HZ);
req.allPurchasePass = any(finiteFvec) && all(fvecArr(finiteFvec) >= PURCHASE_TARGET_BW_HZ);

fprintf("\nRequirement checks:\n");
fprintf("  M3 crossover requirement        : %.2f Hz -> %s\n", ...
    req.m3CrossoverHz, ternaryStr(req.allM3Pass, "PASS", "FAIL"));
fprintf("  Purchase-facing bandwidth target: %.2f Hz -> %s\n", ...
    req.purchaseTargetHz, ternaryStr(req.allPurchasePass, "PASS", "FAIL"));
fprintf("  Measured f_vec range            : %.2f .. %.2f Hz\n", ...
    req.minMeasuredFvecHz, req.maxMeasuredFvecHz);

%% Plots

cCorner = [0 0.7 1]; cKnee = [1 0.55 0]; cVec = [0.45 1 0.45];
cReq = [0.95 0.2 0.5]; cPts = [1 1 1];

% (1) f_vec vs angle amplitude
figVec = figure("Name", "amp_sweep_fvec", "Color", "w"); hold on; grid on;
plot(thetaArr, fcArr,   "-o", "Color", cCorner, "LineWidth", 1.8, "MarkerFaceColor", cCorner, "DisplayName", "linear corner f_c");
plot(thetaArr, kneeArr, "-s", "Color", cKnee,   "LineWidth", 1.8, "MarkerFaceColor", cKnee,   "DisplayName", "slew knee f_{slew}");
plot(thetaArr, fvecArr, "-^", "Color", cVec,    "LineWidth", 2.4, "MarkerFaceColor", cVec,    "DisplayName", "f_{vec} = min");
yline(COH_CEILING_HZ, ":", "coherence ceiling", "Color", [0.5 0.5 0.5]);
yline(req.m3CrossoverHz, "--", sprintf("M3 crossover %.2f Hz", req.m3CrossoverHz), ...
    "Color", cReq, "LineWidth", 1.4, "DisplayName", "M3 required crossover");
yline(req.purchaseTargetHz, "-.", sprintf("purchase target %.1f Hz", req.purchaseTargetHz), ...
    "Color", [0.65 0.2 1.0], "LineWidth", 1.4, "DisplayName", "purchase target");
xlabel("angle amplitude \theta_{amp} [deg]"); ylabel("bandwidth [Hz]");
title("Achievable vectoring bandwidth vs angle amplitude");
legend("Location", "northeast");

% (2) tau and delay vs amplitude (amplitude-dependence of the linear model)
figMod = figure("Name", "amp_sweep_model", "Color", "w");
tiledlayout(2,1,"TileSpacing","compact");
nexttile; hold on; grid on;
plot(thetaArr, [rung.tau_s].'*1e3, "-o", "Color", cCorner, "LineWidth", 1.8, ...
    "MarkerFaceColor", cCorner, "DisplayName", "time constant \tau");
ylabel("\tau [ms]"); title("Linear FOPD parameters vs amplitude");
legend("Location", "best");
nexttile; hold on; grid on;
plot(thetaArr, [rung.delay_s].'*1e3, "-s", "Color", cKnee, "LineWidth", 1.8, ...
    "MarkerFaceColor", cKnee, "DisplayName", "delay L");
xlabel("angle amplitude \theta_{amp} [deg]"); ylabel("delay L [ms]");
legend("Location", "best");

% (3) probe describing-function: gain droop + THD per probed rung
figProbe = figure("Name", "amp_sweep_probe", "Color", "w");
tiledlayout(2,1,"TileSpacing","compact");
axG = nexttile; hold(axG,"on"); grid(axG,"on");
axT = nexttile; hold(axT,"on"); grid(axT,"on");
probedAny = false;
cmap = lines(nRung);
for i = 1:nRung
    if isempty(rung(i).probe_f), continue; end
    probedAny = true;
    lbl = sprintf("%.0f deg", rung(i).theta_deg);
    plot(axG, rung(i).probe_f, rung(i).probe_droopDb, "-o", "Color", cmap(i,:), "LineWidth", 1.6, "DisplayName", lbl);
    plot(axT, rung(i).probe_f, rung(i).probe_thd,     "-o", "Color", cmap(i,:), "LineWidth", 1.6, "DisplayName", lbl);
end
if probedAny
    yline(axG, -GAIN_DROOP_DB, "--", sprintf("-%.0f dB", GAIN_DROOP_DB), "Color", [0.5 0.5 0.5]);
    yline(axT, THD_THRESH, "--", sprintf("THD %.0f%%", THD_THRESH*100), "Color", [0.5 0.5 0.5]);
end
ylabel(axG, "gain droop [dB]"); title(axG, "Slew probes: gain droop and THD (knee detectors)");
xlabel(axT, "probe frequency [Hz]"); ylabel(axT, "angle THD");
legend(axG, "Location", "southwest");

%% Report

reportPath = fullfile(reportDir, "analyze_servo_prps_amplitude_sweep.report.md");
writeSweepReport(reportPath, dataDir, csvFiles, rung, ...
    SLEW_EST_DEG_S, CORNER_EST_HZ, COH_CEILING_HZ, GAIN_DROOP_DB, THD_THRESH, req);
fprintf("\nReport written to:\n  %s\n", reportPath);

%% Save

summaryCsvPath = fullfile(processedDir, "servo_prps_amplitude_bandwidth_summary.csv");
probeCsvPath = fullfile(processedDir, "servo_prps_amplitude_slew_probe_summary.csv");
matPath = fullfile(processedDir, "analyze_servo_prps_amplitude_sweep.mat");
writetable(summaryTable, summaryCsvPath);
if ~isempty(probeTable)
    writetable(probeTable, probeCsvPath);
end

if SAVE_FIGURES
    if ~exist(plotDir, "dir"), mkdir(plotDir); end
    saveAllFiguresIfEnabled(SAVE_FIGURES, plotDir);
end
save(matPath, ...
    "rung", "thetaArr", "fcArr", "kneeArr", "fvecArr", "req", ...
    "summaryTable", "probeTable", "FRF_OPTS", "FIT_OPTS", ...
    "SLEW_EST_DEG_S", "CORNER_EST_HZ", "COH_CEILING_HZ", "DATASET_STATUS");
fprintf("Processed summary written to:\n  %s\n", summaryCsvPath);
if ~isempty(probeTable)
    fprintf("Probe summary written to:\n  %s\n", probeCsvPath);
end
fprintf("MAT artifact written to:\n  %s\n", matPath);

%% ----------------------------------------------------------------------
%% Local functions
%% ----------------------------------------------------------------------

function tag = ladderTagOf(runNames)
    % Extract the "aNN" rung tag from a "ladder_aNN_..." run_name.
    tag = strings(numel(runNames), 1);
    for i = 1:numel(runNames)
        tok = regexp(runNames(i), "ladder_(a\d+)_", "tokens", "once");
        if ~isempty(tok), tag(i) = tok{1}; else, tag(i) = "a00"; end
    end
end

function edgeHz = contiguousCoherenceEdge(frf, thresh)
    edgeHz = NaN;
    [f, idx] = sort(frf.f_Hz(:)); coh = frf.coherence(idx);
    for i = 1:numel(f)
        if coh(i) >= thresh, edgeHz = f(i); else, break; end
    end
end

function meas = measureProbeTone(Dp, dt_s, nHarm)
    % Coherently average one period, FFT, read the fundamental gain
    % theta/command and the angle THD (harmonic power / fundamental power).
    meas = [];
    [u, y] = ServoPrpsId.makeUniformPeriodVectors(Dp);
    N = numel(u);
    if N < 20, return; end

    U = fft(u); Y = fft(y);
    Umag = abs(U(1:floor(N/2)));
    Umag(1) = 0;                       % ignore DC
    [~, kFund] = max(Umag);            % fundamental bin (0-based freq index kFund-? )
    kIdx = kFund;                      % MATLAB 1-based; frequency bin number = kIdx-1
    binNo = kIdx - 1;
    if binNo < 1, return; end

    % Effective period length in seconds from the sample grid + nominal dt.
    period_s = N * dt_s;
    meas.f_hz = binNo / period_s;

    Ufund = U(kIdx); Yfund = Y(kIdx);
    if abs(Ufund) <= 0, return; end
    meas.gain_abs = abs(Yfund) / abs(Ufund);   % rad/us
    meas.phase_deg = angle(Yfund / Ufund) * 180/pi;

    % Angle THD: harmonic bins h*binNo (guard against Nyquist wrap).
    harmPow = 0;
    for h = 2:nHarm
        hk = h*binNo + 1;              % 1-based index of harmonic
        if hk > floor(N/2), break; end
        harmPow = harmPow + abs(Y(hk))^2;
    end
    fundPow = abs(Yfund)^2;
    if fundPow <= 0, meas.thd = NaN; else, meas.thd = sqrt(harmPow / fundPow); end
end

function [kneeHz, src] = findKnee(f, droopDb, thd, droopThreshDb, thdThresh)
    % Lowest frequency where gain droops past -droopThreshDb OR THD >= thdThresh.
    % Linear interpolation (in log-f) at the crossing; if neither criterion
    % triggers within the probed range, return the top probed freq (lower bound).
    f = f(:); droopDb = droopDb(:); thd = thd(:);
    kneeGain = crossFreq(f, droopDb, -droopThreshDb, "below");
    kneeThd  = crossFreq(f, thd, thdThresh, "above");
    cands = [kneeGain, kneeThd];
    srcs  = ["gain-" + string(droopThreshDb) + "dB", "THD-" + string(round(thdThresh*100)) + "%"];
    valid = isfinite(cands);
    if any(valid)
        [kneeHz, w] = min(cands(valid));
        vsrc = srcs(valid); src = vsrc(w);
    else
        kneeHz = max(f); src = "not reached (>= top probe)";
    end
end

function fc = crossFreq(f, y, thresh, dir)
    % First crossing of y past thresh, interpolated in log-frequency.
    fc = NaN;
    for i = 1:numel(f)
        hit = (dir == "below" && y(i) <= thresh) || (dir == "above" && y(i) >= thresh);
        if hit
            if i == 1
                fc = f(1);
            else
                % interpolate between i-1 and i in log-f vs y
                x1 = log(f(i-1)); x2 = log(f(i));
                y1 = y(i-1);      y2 = y(i);
                if y2 == y1, fc = f(i); else, fc = exp(x1 + (thresh - y1)*(x2 - x1)/(y2 - y1)); end
            end
            return;
        end
    end
end

function writeSweepReport(path, dataDir, csvFiles, rung, ...
        slewEst, cornerEst, cohCeil, droopDb, thdThresh, req)
    fid = fopen(path, "w");
    if fid < 0, error("Could not open report:\n%s", path); end
    cleanup = onCleanup(@() fclose(fid));

    fprintf(fid, "# Servo PRPS Amplitude-Bandwidth Sweep Report\n\n");
    generatedAt = datetime("now", "Format", "yyyy-MM-dd HH:mm:ss");
    fprintf(fid, "**Generated:** %s  \n", char(generatedAt));
    fprintf(fid, "**Dataset:** `%s`  \n", strrep(char(dataDir), "\", "/"));
    fprintf(fid, "**CSV files:** %d  \n", numel(csvFiles));
    fprintf(fid, "**Rungs:** %d\n\n", numel(rung));

    fprintf(fid, "Upgraded-servo context (2026-06-29 step test): slew_est **%.0f deg/s**, ", slewEst);
    fprintf(fid, "corner **%.1f Hz**, coherence ceiling **%.1f Hz**. ", cornerEst, cohCeil);
    fprintf(fid, "Knee criteria: gain droop >= %.0f dB OR angle THD >= %.0f%%.\n\n", droopDb, thdThresh*100);

    fprintf(fid, "## Per-rung results\n\n");
    fprintf(fid, "| theta (deg) | amp (us) | K (rad/us) | tau (ms) | corner f_c (Hz) | slew knee (Hz) | knee source | f_vec (Hz) |\n");
    fprintf(fid, "|---:|---:|---:|---:|---:|---:|---|---:|\n");
    for i = 1:numel(rung)
        r = rung(i);
        fprintf(fid, "| %.0f | %.0f | %.4g | %.1f | %.2f | %.2f | %s | **%.2f** |\n", ...
            r.theta_deg, r.amp_us, r.K, r.tau_s*1e3, r.fc_hz, r.knee_hz, r.knee_source, r.f_vec_hz);
    end
    fprintf(fid, "\n");

    fprintf(fid, "## Effective vectoring bandwidth\n\n");
    fprintf(fid, "f_vec(theta) = min(linear corner, slew knee): corner-limited (roughly flat) at\n");
    fprintf(fid, "small amplitude, slew-limited (~1/theta) once f_slew drops below the corner.\n\n");

    fprintf(fid, "## Requirement checks\n\n");
    fprintf(fid, "| Check | Threshold (Hz) | Measured f_vec range (Hz) | Result |\n");
    fprintf(fid, "|---|---:|---:|---|\n");
    fprintf(fid, "| M3 disturbance-rejection crossover | %.2f | %.2f-%.2f | **%s** |\n", ...
        req.m3CrossoverHz, req.minMeasuredFvecHz, req.maxMeasuredFvecHz, ...
        ternaryStr(req.allM3Pass, "PASS", "FAIL"));
    fprintf(fid, "| Purchase-facing bandwidth target | %.2f | %.2f-%.2f | **%s** |\n\n", ...
        req.purchaseTargetHz, req.minMeasuredFvecHz, req.maxMeasuredFvecHz, ...
        ternaryStr(req.allPurchasePass, "PASS", "FAIL"));

    fprintf(fid, "Interpretation: the measured servo clears the true M3 crossover if the pass ");
    fprintf(fid, "above is green. The separate purchase-facing target is a margin/spec target ");
    fprintf(fid, "used for hardware selection, not the literal M3 closed-loop crossover.\n\n");

    clear cleanup;
end

function s = ternaryStr(cond, a, b)
    if cond, s = a; else, s = b; end
end
