%% analyze_servo_prps_two_band.m
% Two-band servo PRPS analysis for the re-run campaign.
%
% Campaign (see firmware servo_prps_log.orchestrate.json, generated by
% tools/design_servo_prps_excitation.py --combined):
%   - Large-signal LOW band  (~0.3-3.4 Hz, +/-11 deg): clears the +/-2 deg
%     backlash, so it is the operating-amplitude regime the stabilizer lives in.
%   - Small-signal HIGH band (~0.3-10.75 Hz, +/-5 deg): crosses the ~3.4 Hz
%     step-reconstruction corner to MEASURE the rolloff/phase the prior pass had
%     to extrapolate.
%
% Strategy (docs: experiments/servo_identification/results.md "Transition";
% memory prps-rerun-two-band-strategy):
%   1. Pool the low-band realizations -> low-band FRF -> fit the nominal FOPD.
%   2. Bootstrap the low band -> (K,tau,L) cloud -> a CI tube on the Bode plot.
%   3. Pool the high-band realizations -> high-band FRF.
%   4. The bands OVERLAP on 0.3-3.4 Hz, so the same frequencies are measured at
%      two amplitudes. Test whether the high-band FRF lies inside the low-band
%      fit's CI tube:
%        - overlap region  -> amplitude-dependence test (same f, two amplitudes)
%        - extension region (> low-band max f) -> does small-signal rolloff match
%          the low-band model's extrapolation?
%   5. DECISION:
%        - MERGE  (both fractions-inside >= threshold): refit one wide-band FOPD
%          on the union -> amplitude-dependence negligible, corner now measured.
%        - SEPARATE: keep the low band as the nominal model and route the
%          high-band deviation to a high-frequency multiplicative uncertainty
%          W(f) for robust Stage 2 design.
%
% This script does NOT blindly stack the two bands into one fit; the data picks
% the branch via a quantitative CI test.
%
% Empirical transfer function: G(jw) = theta_rad(jw) / command_delta_us(jw)  [rad/us]

clearvars -except N_BOOT DATASET_STATUS RNG_SEED SAVE_FIGURES;
clc; close all;

%% User options

if ~exist("SAVE_FIGURES", "var"),   SAVE_FIGURES = true;         end
if ~exist("DATASET_STATUS", "var"), DATASET_STATUS = "candidate"; end
if ~exist("N_BOOT", "var"),         N_BOOT = 300;                end
if ~exist("RNG_SEED", "var"),       RNG_SEED = 1;                end

DATASET_STATUS = string(DATASET_STATUS);

% Band classification by run_name prefix (set by the generator's segment names).
LOW_BAND_PATTERN  = "lowband";
HIGH_BAND_PATTERN = "highband";

% Step-reconstruction corner (Hz), for annotation / band framing.
CORNER_HZ = 3.4;

% Merge decision thresholds: fraction of high-band points that must fall inside
% the low-band fit's bootstrap CI tube.
MERGE_OVERLAP_FRACTION   = 0.70;   % same-frequency amplitude-dependence test
MERGE_EXTENSION_FRACTION = 0.60;   % model-extrapolation (rolloff) test, looser

% Coherence threshold that defines the trusted upper band edge.
COHERENCE_BAND_EDGE = 0.90;

%% Servo / PRPS settings

COUNTS_PER_REV          = 2400.0;
DEFAULT_SERVO_CENTER_US = 1450;
SERVO_OUTPUT_SIGN       = -1;       % command_delta_us up -> theta down; flip to positive-gain plant
DEFAULT_FREQ_LABEL      = "0p3_to_10p75Hz";

MIN_COHERENCE_FOR_FIT = 0.60;

% FRF extraction (ServoPrpsId.estimatePrpsFrfFromTable opts). The re-run uses a
% 5 ms command update (200 Hz) but logs every LOG_EVERY_N_TICKS=4 ticks, so the
% LOGGED sample period is 5 ms * 4 = 20 ms (50 Hz, Nyquist 25 Hz) over a 40 s
% PRPS period. The FRF frequency axis is built from logged rows, so dt_s must be
% the logged-sample period (0.020), NOT the command update period. span covers
% both bands.
FRF_OPTS = struct();
FRF_OPTS.inferFreqsFromInput       = true;
FRF_OPTS.freqListHz                = [];
FRF_OPTS.inputBinRelativeThreshold = 0.05;
FRF_OPTS.freqMinHz                 = 0.2;
FRF_OPTS.freqMaxHz                 = 12.0;
FRF_OPTS.removePeriodMean          = true;
FRF_OPTS.detrendEachPeriod         = false;
FRF_OPTS.minPeriodsPerRun          = 2;
FRF_OPTS.minSamplesPerPeriod       = 20;
FRF_OPTS.useNominalCommandDtForFrf = true;
FRF_OPTS.nominalCommandDtS         = 0.020;   % logged-sample period = 5 ms command * LOG_EVERY_N_TICKS (4)

% FOPD fit (ServoPrpsId.fitOneFrequencyModel opts).
FIT_OPTS = struct();
FIT_OPTS.weightingMode             = "relative_with_coh";
FIT_OPTS.gainFloorMode             = "fraction_of_median";
FIT_OPTS.gainFloorFractionOfMedian = 0.20;
FIT_OPTS.manualGainFloor           = 1e-5;
FIT_OPTS.initialK                  = pi / 2000;
FIT_OPTS.initialTau                = 0.024;
FIT_OPTS.initialDelay              = 0.029;
FIT_OPTS.initialTau2               = 0.02;
FIT_OPTS.minTau                    = 0.005;
FIT_OPTS.maxTau                    = 2.0;
FIT_OPTS.minDelay                  = 0.0;
FIT_OPTS.maxDelay                  = 0.50;
FIT_OPTS.minGainAbs                = 1e-5;
FIT_OPTS.maxGainAbs                = 0.01;
FIT_OPTS.maxIter                   = 5000;
FIT_OPTS.maxEval                   = 10000;

%% Locate data / output folders

scriptPath = mfilename("fullpath");
repoRoot   = findRepoRoot(scriptPath);
addpath(fullfile(repoRoot, "analysis", "utils"));

dataDir = getMirroredRawDataDir(scriptPath, DATASET_STATUS);
plotDir = getMirroredPlotDir(scriptPath);

if ~isfolder(dataDir)
    error("Data folder not found:\n%s", dataDir);
end

csvFiles = dir(fullfile(dataDir, "*.csv"));
if isempty(csvFiles)
    error("No CSV files found in:\n%s\nRun the combined two-band campaign first.", dataDir);
end
[~, sortIdx] = sort(string({csvFiles.name}));
csvFiles = csvFiles(sortIdx);

fprintf("\nServo PRPS two-band analysis\n");
fprintf("  Dataset: %s\n", dataDir);
fprintf("  CSV files: %d\n", numel(csvFiles));

%% Load and normalize

Tall = ServoPrpsId.readCombinedCsvTables(csvFiles);
Tall = ServoPrpsId.normalizeServoPrpsTable( ...
    Tall, COUNTS_PER_REV, DEFAULT_SERVO_CENTER_US, DEFAULT_FREQ_LABEL, SERVO_OUTPUT_SIGN);

% Keep only the PRPS segment (drop baseline/settle holds).
Tall = Tall(strcmpi(string(Tall.segment), "prps"), :);
if isempty(Tall)
    error("No PRPS-segment rows found after filtering.");
end

runNamesAll = unique(string(Tall.run_name), "stable");
isLow  = startsWith(runNamesAll, LOW_BAND_PATTERN);
isHigh = startsWith(runNamesAll, HIGH_BAND_PATTERN);

lowRunNames  = runNamesAll(isLow);
highRunNames = runNamesAll(isHigh);

fprintf("  Low-band realizations:  %d  (%s)\n", numel(lowRunNames), strjoin(lowRunNames, ", "));
fprintf("  High-band realizations: %d  (%s)\n", numel(highRunNames), strjoin(highRunNames, ", "));

if isempty(lowRunNames)
    error("No low-band runs found (pattern ""%s""). Check run_name prefixes.", LOW_BAND_PATTERN);
end
if isempty(highRunNames)
    error("No high-band runs found (pattern ""%s""). Check run_name prefixes.", HIGH_BAND_PATTERN);
end

Tlow  = ServoPrpsId.cleanServoPrpsTable(Tall(ismember(string(Tall.run_name), lowRunNames), :));
Thigh = ServoPrpsId.cleanServoPrpsTable(Tall(ismember(string(Tall.run_name), highRunNames), :));

%% Pooled FRFs per band (averages across realizations + periods)

lowFrf  = ServoPrpsId.estimatePrpsFrfFromTable(Tlow,  "low_band_pooled",  "low",  FRF_OPTS);
highFrf = ServoPrpsId.estimatePrpsFrfFromTable(Thigh, "high_band_pooled", "high", FRF_OPTS);

if isempty(lowFrf.f_Hz)
    error("Low-band FRF is empty.");
end
if isempty(highFrf.f_Hz)
    error("High-band FRF is empty.");
end

lowMaxF = max(lowFrf.f_Hz);
fprintf("\n  Low-band FRF:  %d lines, %.3f-%.3f Hz\n",  numel(lowFrf.f_Hz),  min(lowFrf.f_Hz),  lowMaxF);
fprintf("  High-band FRF: %d lines, %.3f-%.3f Hz\n", numel(highFrf.f_Hz), min(highFrf.f_Hz), max(highFrf.f_Hz));

% Trusted upper band edge from high-band coherence.
cohEdgeHz = highBandCoherenceEdge(highFrf, COHERENCE_BAND_EDGE);
if isfinite(cohEdgeHz)
    fprintf("  High-band coherence >= %.2f up to %.3f Hz (trusted upper edge)\n", COHERENCE_BAND_EDGE, cohEdgeHz);
else
    fprintf("  High-band coherence never reaches %.2f in band.\n", COHERENCE_BAND_EDGE);
end

%% Nominal fit on the LOW band

lowFitMask = lowFrf.coherence >= MIN_COHERENCE_FOR_FIT & isfinite(lowFrf.G_emp);
if nnz(lowFitMask) < 2
    error("Fewer than 2 coherent low-band FRF points; cannot fit nominal model.");
end

lowModel = ServoPrpsId.fitOneFrequencyModel( ...
    "first_order_delay", ...
    lowFrf.f_Hz(lowFitMask), lowFrf.G_emp(lowFitMask), lowFrf.coherence(lowFitMask), FIT_OPTS);

fprintf("\nNominal LOW-band FOPD (operating-amplitude model):\n");
fprintf("  K     = %.6g rad/us\n", lowModel.K);
fprintf("  tau   = %.4g ms\n", lowModel.tau1_s * 1e3);
fprintf("  delay = %.4g ms\n", lowModel.delay_s * 1e3);

%% Bootstrap the LOW band -> (K,tau,L) cloud -> CI tube

rng(RNG_SEED, "twister");
lowUnits = buildPeriodUnits(Tlow, FRF_OPTS.minSamplesPerPeriod);
if isempty(lowUnits)
    error("No low-band bootstrap units (check period_index / sample counts).");
end
lowUnitRun = string({lowUnits.run_name}).';
lowUnitRunNames = unique(lowUnitRun, "stable");

bootK = NaN(N_BOOT, 1); bootTau = NaN(N_BOOT, 1); bootDelay = NaN(N_BOOT, 1);

fprintf("\nBootstrapping low band (%d draws, stratified by realization)...\n", N_BOOT);
for b = 1:N_BOOT
    sampledIdx = drawStratifiedUnits(lowUnitRun, lowUnitRunNames);
    synthTrain = assembleSyntheticTable(lowUnits, sampledIdx, FRF_OPTS.nominalCommandDtS);

    try
        bf = ServoPrpsId.estimatePrpsFrfFromTable(synthTrain, "boot_" + b, "boot", FRF_OPTS);
        m = bf.coherence >= MIN_COHERENCE_FOR_FIT & isfinite(bf.G_emp);
        if nnz(m) < 2
            continue;
        end
        bm = ServoPrpsId.fitOneFrequencyModel("first_order_delay", ...
            bf.f_Hz(m), bf.G_emp(m), bf.coherence(m), FIT_OPTS);
        bootK(b) = bm.K; bootTau(b) = bm.tau1_s; bootDelay(b) = bm.delay_s;
    catch ME
        warning("Bootstrap draw %d failed: %s", b, ME.message);
    end

    if mod(b, max(1, floor(N_BOOT/10))) == 0 || b == N_BOOT
        fprintf("  %d / %d\n", b, N_BOOT);
    end
end

okBoot = isfinite(bootK) & bootK > 0 & isfinite(bootTau) & bootTau > 0 & isfinite(bootDelay) & bootDelay >= 0;
bootK = bootK(okBoot); bootTau = bootTau(okBoot); bootDelay = bootDelay(okBoot);
nBootOk = numel(bootK);
if nBootOk < 10
    error("Too few successful bootstrap draws (%d).", nBootOk);
end

ci = struct();
ci.K_p2p5     = prctileLocal(bootK, 2.5);    ci.K_p97p5     = prctileLocal(bootK, 97.5);
ci.tau_p2p5   = prctileLocal(bootTau, 2.5);  ci.tau_p97p5   = prctileLocal(bootTau, 97.5);
ci.delay_p2p5 = prctileLocal(bootDelay, 2.5);ci.delay_p97p5 = prctileLocal(bootDelay, 97.5);

fprintf("\nLow-band bootstrap 95%% CI (%d draws):\n", nBootOk);
fprintf("  K     : %.6g - %.6g rad/us\n", ci.K_p2p5, ci.K_p97p5);
fprintf("  tau   : %.4g - %.4g ms\n", ci.tau_p2p5*1e3, ci.tau_p97p5*1e3);
fprintf("  delay : %.4g - %.4g ms\n", ci.delay_p2p5*1e3, ci.delay_p97p5*1e3);

%% Evaluate the CI tube at the high-band frequencies and test membership

wHigh = 2*pi*highFrf.f_Hz(:);
Gcloud = evalCloud(bootK, bootTau, bootDelay, wHigh);    % [nHigh x nBootOk]

magCloudDb = 20*log10(abs(Gcloud));
phCloud    = unwrapAnchorCols(angle(Gcloud)) * 180/pi;

magHiEmpDb = 20*log10(abs(highFrf.G_emp(:)));
phHiEmp    = unwrapAnchor(angle(highFrf.G_emp(:))) * 180/pi;

magLo = rowPrctile(magCloudDb, 2.5);  magHi = rowPrctile(magCloudDb, 97.5);
phLo  = rowPrctile(phCloud, 2.5);     phHi  = rowPrctile(phCloud, 97.5);

inMag = magHiEmpDb >= magLo & magHiEmpDb <= magHi;
inPh  = phHiEmp    >= phLo  & phHiEmp    <= phHi;
inTube = inMag & inPh;

% Only judge membership where the high-band point is itself trustworthy.
hiCoh = highFrf.coherence(:) >= MIN_COHERENCE_FOR_FIT;

isOverlap   = highFrf.f_Hz(:) <= lowMaxF + 1e-9;
isExtension = ~isOverlap;

overlapJudged = isOverlap & hiCoh;
extJudged     = isExtension & hiCoh;

overlapFrac = safeFraction(inTube(overlapJudged));
extFrac     = safeFraction(inTube(extJudged));

fprintf("\nHigh-band vs low-band CI tube:\n");
fprintf("  Overlap (<= %.2f Hz): %d/%d points inside tube (%.0f%%)\n", ...
    lowMaxF, nnz(inTube & overlapJudged), nnz(overlapJudged), 100*overlapFrac);
fprintf("  Extension (> %.2f Hz): %d/%d points inside tube (%.0f%%)\n", ...
    lowMaxF, nnz(inTube & extJudged), nnz(extJudged), 100*extFrac);

doMerge = overlapFrac >= MERGE_OVERLAP_FRACTION && extFrac >= MERGE_EXTENSION_FRACTION;

%% Branch: MERGE (wide-band refit) or SEPARATE (nominal + uncertainty)

mergedModel = struct([]);
W = struct();   % high-frequency multiplicative uncertainty (separate branch)

if doMerge
    fprintf("\nDECISION: MERGE. Amplitude-dependence negligible across bands; refit wide-band FOPD.\n");

    uF   = [lowFrf.f_Hz(lowFitMask);  highFrf.f_Hz(hiCoh)];
    uG   = [lowFrf.G_emp(lowFitMask); highFrf.G_emp(hiCoh)];
    uCoh = [lowFrf.coherence(lowFitMask); highFrf.coherence(hiCoh)];

    mergedModel = ServoPrpsId.fitOneFrequencyModel("first_order_delay", uF, uG, uCoh, FIT_OPTS);

    fprintf("Wide-band FOPD (final model):\n");
    fprintf("  K     = %.6g rad/us\n", mergedModel.K);
    fprintf("  tau   = %.4g ms\n", mergedModel.tau1_s * 1e3);
    fprintf("  delay = %.4g ms\n", mergedModel.delay_s * 1e3);
    finalModel = mergedModel;
else
    fprintf("\nDECISION: SEPARATE. Low band = nominal; high-band deviation -> HF uncertainty W(f).\n");

    GlowAtHigh = ServoPrpsId.evalFrequencyModel("first_order_delay", lowModel.params, wHigh);
    wRel = abs(highFrf.G_emp(:) - GlowAtHigh) ./ max(abs(GlowAtHigh), FIT_OPTS.manualGainFloor);

    W.f_Hz      = highFrf.f_Hz(:);
    W.w_rel     = wRel;
    W.coherence = highFrf.coherence(:);
    W.max_overlap   = maxOver(wRel, overlapJudged);
    W.max_extension = maxOver(wRel, extJudged);

    fprintf("Multiplicative uncertainty (relative): overlap max %.2f, extension max %.2f\n", ...
        W.max_overlap, W.max_extension);
    finalModel = lowModel;
end

%% Plots

% Bode: low CI tube + low fit + low FRF + high FRF (overlap/extension)
figBode = figure("Name", "two_band_bode", "Color", "w");
tiledlayout(2, 1, "TileSpacing", "compact");

fGrid = logspace(log10(FRF_OPTS.freqMinHz), log10(FRF_OPTS.freqMaxHz), 240).';
wGrid = 2*pi*fGrid;
GcloudGrid = evalCloud(bootK, bootTau, bootDelay, wGrid);
magGridLo = rowPrctile(20*log10(abs(GcloudGrid)), 2.5);
magGridHi = rowPrctile(20*log10(abs(GcloudGrid)), 97.5);
phGridLo  = rowPrctile(unwrapAnchorCols(angle(GcloudGrid))*180/pi, 2.5);
phGridHi  = rowPrctile(unwrapAnchorCols(angle(GcloudGrid))*180/pi, 97.5);

GlowGrid = ServoPrpsId.evalFrequencyModel("first_order_delay", lowModel.params, wGrid);

cTube = [0 0.75 0.9]; cLow = [0 0.45 0.95]; cLowPts = [1 0.65 0];
cOver = [0.2 0.85 0.2]; cExt = [0.85 0.2 0.85]; cMerge = [0.95 0.95 0.2];

nexttile; hold on; grid on;
fill([fGrid; flipud(fGrid)], [magGridLo; flipud(magGridHi)], cTube, "FaceAlpha", 0.25, "EdgeColor", "none");
semilogx(fGrid, 20*log10(abs(GlowGrid)), "Color", cLow, "LineWidth", 1.8);
scatter(lowFrf.f_Hz, 20*log10(abs(lowFrf.G_emp)), 30, cLowPts, "filled");
scatter(highFrf.f_Hz(isOverlap), 20*log10(abs(highFrf.G_emp(isOverlap))), 26, cOver, "filled");
scatter(highFrf.f_Hz(isExtension), 20*log10(abs(highFrf.G_emp(isExtension))), 26, cExt, "filled");
if doMerge
    semilogx(fGrid, 20*log10(abs(ServoPrpsId.evalFrequencyModel("first_order_delay", mergedModel.params, wGrid))), ...
        "--", "Color", cMerge, "LineWidth", 1.6);
end
xline(CORNER_HZ, ":", "corner", "Color", [0.4 0.4 0.4]);
set(gca, "XScale", "log");
ylabel("Magnitude (dB rad/us)");
title("Two-band servo PRPS: low-band fit + CI tube vs high-band FRF");
legendStrings = ["low 95% CI tube", "low FOPD fit", "low FRF (large-signal)", ...
    "high FRF overlap", "high FRF extension"];
if doMerge, legendStrings(end+1) = "wide-band refit"; end
legend(legendStrings, "Location", "southwest");

nexttile; hold on; grid on;
fill([fGrid; flipud(fGrid)], [phGridLo; flipud(phGridHi)], cTube, "FaceAlpha", 0.25, "EdgeColor", "none");
semilogx(fGrid, unwrapAnchor(angle(GlowGrid))*180/pi, "Color", cLow, "LineWidth", 1.8);
scatter(lowFrf.f_Hz, unwrapAnchor(angle(lowFrf.G_emp))*180/pi, 30, cLowPts, "filled");
scatter(highFrf.f_Hz(isOverlap), phHiEmp(isOverlap), 26, cOver, "filled");
scatter(highFrf.f_Hz(isExtension), phHiEmp(isExtension), 26, cExt, "filled");
xline(CORNER_HZ, ":", "Color", [0.4 0.4 0.4]);
set(gca, "XScale", "log");
xlabel("Frequency (Hz)"); ylabel("Phase (deg)");

% Coherence by band
figCoh = figure("Name", "two_band_coherence", "Color", "w"); %#ok<NASGU>
hold on; grid on;
scatter(lowFrf.f_Hz, lowFrf.coherence, 30, cLowPts, "filled");
scatter(highFrf.f_Hz, highFrf.coherence, 26, cExt, "filled");
yline(COHERENCE_BAND_EDGE, "--", sprintf("gamma^2 = %.2f", COHERENCE_BAND_EDGE), "Color", [0.4 0.4 0.4]);
if isfinite(cohEdgeHz), xline(cohEdgeHz, ":", sprintf("%.2f Hz", cohEdgeHz), "Color", [0.4 0.4 0.4]); end
set(gca, "XScale", "log"); ylim([0 1.05]);
xlabel("Frequency (Hz)"); ylabel("Coherence \gamma^2");
title("Coherence by band"); legend(["low band", "high band"], "Location", "southwest");

% Uncertainty plot (separate branch only)
if ~doMerge
    figW = figure("Name", "two_band_hf_uncertainty", "Color", "w"); %#ok<NASGU>
    hold on; grid on;
    stem(W.f_Hz, W.w_rel, "filled", "Color", cExt);
    xline(lowMaxF, ":", "low-band edge", "Color", [0.4 0.4 0.4]);
    set(gca, "XScale", "log");
    xlabel("Frequency (Hz)"); ylabel("Relative deviation |G_{emp}/G_{low} - 1|");
    title("High-frequency multiplicative uncertainty W(f)");
end

%% Report

reportPath = fullfile(plotDir, "analyze_servo_prps_two_band.report.md");
writeTwoBandReport(reportPath, dataDir, csvFiles, lowRunNames, highRunNames, ...
    lowFrf, highFrf, lowMaxF, cohEdgeHz, COHERENCE_BAND_EDGE, ...
    lowModel, ci, nBootOk, overlapFrac, extFrac, ...
    MERGE_OVERLAP_FRACTION, MERGE_EXTENSION_FRACTION, doMerge, mergedModel, W);

fprintf("\nReport written to:\n  %s\n", reportPath);

%% Save figures + data

if SAVE_FIGURES
    if ~exist(plotDir, "dir"), mkdir(plotDir); end
    saveAllFiguresIfEnabled(SAVE_FIGURES, plotDir);
end

save(fullfile(plotDir, "analyze_servo_prps_two_band.mat"), ...
    "lowFrf", "highFrf", "lowModel", "ci", "bootK", "bootTau", "bootDelay", ...
    "doMerge", "mergedModel", "W", "overlapFrac", "extFrac", "cohEdgeHz", ...
    "FRF_OPTS", "FIT_OPTS", "DATASET_STATUS");

%% ----------------------------------------------------------------------
%% Local functions
%% ----------------------------------------------------------------------

function edgeHz = highBandCoherenceEdge(frf, thresh)
    % Highest contiguous-from-low frequency where coherence stays >= thresh.
    edgeHz = NaN;
    [f, idx] = sort(frf.f_Hz(:));
    coh = frf.coherence(idx);
    for i = 1:numel(f)
        if coh(i) >= thresh
            edgeHz = f(i);
        else
            break;
        end
    end
end

function units = buildPeriodUnits(T, minSamplesPerPeriod)
    units = struct("unit_id", {}, "run_name", {}, "source_file_index", {}, ...
        "period_index", {}, "data", {});

    fileIds = unique(ServoPrpsId.forceNumeric(T.source_file_index), "stable");
    for f = 1:numel(fileIds)
        fileIdx = fileIds(f);
        Dfile = T(ServoPrpsId.forceNumeric(T.source_file_index) == fileIdx, :);
        rNames = unique(string(Dfile.run_name), "stable");

        for r = 1:numel(rNames)
            Drun = Dfile(string(Dfile.run_name) == rNames(r), :);
            periodIds = unique(ServoPrpsId.forceNumeric(Drun.period_index), "stable");
            periodIds = periodIds(periodIds >= 0);

            for p = 1:numel(periodIds)
                Dp = Drun(ServoPrpsId.forceNumeric(Drun.period_index) == periodIds(p), :);
                if height(Dp) < minSamplesPerPeriod
                    continue;
                end
                u.unit_id = sprintf("file%03d_p%04d_%s", fileIdx, periodIds(p), matlab.lang.makeValidName(rNames(r)));
                u.run_name = rNames(r);
                u.source_file_index = fileIdx;
                u.period_index = periodIds(p);
                u.data = Dp;
                units(end+1) = u; %#ok<AGROW>
            end
        end
    end
end

function sampledIdx = drawStratifiedUnits(unitRun, runNames)
    sampledIdx = [];
    for r = 1:numel(runNames)
        idx = find(unitRun == runNames(r));
        if isempty(idx), continue; end
        sampledIdx = [sampledIdx; idx(randi(numel(idx), numel(idx), 1))]; %#ok<AGROW>
    end
end

function synth = assembleSyntheticTable(units, sampledIdx, dt_s)
    tables = cell(numel(sampledIdx), 1);
    for i = 1:numel(sampledIdx)
        D = units(sampledIdx(i)).data;
        D.source_file_index = ones(height(D), 1);
        D.period_index = repmat(i - 1, height(D), 1);
        tables{i} = D;
    end
    synth = vertcat(tables{:});
    synth.t_s = (0:height(synth)-1).' * dt_s;
end

function G = evalCloud(K, tau, delay, w)
    n = numel(K);
    G = NaN(numel(w), n);
    for i = 1:n
        params.K = K(i); params.tau1_s = tau(i); params.tau2_s = NaN; params.delay_s = delay(i);
        G(:, i) = ServoPrpsId.evalFrequencyModel("first_order_delay", params, w);
    end
end

function p = unwrapAnchor(theta)
    p = unwrap(theta(:));
    if ~isempty(p)
        p = p - 2*pi*round(p(1) / (2*pi));
    end
end

function P = unwrapAnchorCols(Theta)
    P = unwrap(Theta, [], 1);
    for j = 1:size(P, 2)
        P(:, j) = P(:, j) - 2*pi*round(P(1, j) / (2*pi));
    end
end

function q = rowPrctile(X, pct)
    q = NaN(size(X, 1), 1);
    for i = 1:size(X, 1)
        q(i) = prctileLocal(X(i, :), pct);
    end
end

function q = prctileLocal(x, pct)
    x = sort(x(:)); x = x(isfinite(x));
    if isempty(x), q = NaN; return; end
    if numel(x) == 1, q = x(1); return; end
    pos = 1 + (pct/100) * (numel(x) - 1);
    lo = floor(pos); hi = ceil(pos);
    if lo == hi, q = x(lo); else, q = x(lo) + (pos - lo) * (x(hi) - x(lo)); end
end

function fr = safeFraction(mask)
    mask = mask(:);
    if isempty(mask), fr = NaN; else, fr = nnz(mask) / numel(mask); end
end

function m = maxOver(x, mask)
    v = x(mask);
    if isempty(v), m = NaN; else, m = max(v); end
end

function writeTwoBandReport(path, dataDir, csvFiles, lowRunNames, highRunNames, ...
        lowFrf, highFrf, lowMaxF, cohEdgeHz, cohEdgeThresh, ...
        lowModel, ci, nBootOk, overlapFrac, extFrac, ...
        mergeOverlapThr, mergeExtThr, doMerge, mergedModel, W)

    fid = fopen(path, "w");
    if fid < 0, error("Could not open report:\n%s", path); end
    cleanup = onCleanup(@() fclose(fid));

    fprintf(fid, "# Servo PRPS Two-Band Analysis Report\n\n");
    fprintf(fid, "**Generated:** %s  \n", datestr(now, "yyyy-mm-dd HH:MM:SS"));
    fprintf(fid, "**Dataset:** `%s`  \n", strrep(char(dataDir), "\", "/"));
    fprintf(fid, "**CSV files:** %d  \n", numel(csvFiles));
    fprintf(fid, "**Low-band realizations:** %d  \n", numel(lowRunNames));
    fprintf(fid, "**High-band realizations:** %d\n\n", numel(highRunNames));

    fprintf(fid, "## Bands\n\n");
    fprintf(fid, "| Band | Lines | Range (Hz) | Role |\n|---|---:|---|---|\n");
    fprintf(fid, "| Low (large-signal) | %d | %.3f - %.3f | nominal K/tau/L fit |\n", ...
        numel(lowFrf.f_Hz), min(lowFrf.f_Hz), lowMaxF);
    fprintf(fid, "| High (small-signal) | %d | %.3f - %.3f | rolloff / corner measurement |\n\n", ...
        numel(highFrf.f_Hz), min(highFrf.f_Hz), max(highFrf.f_Hz));

    if isfinite(cohEdgeHz)
        fprintf(fid, "Trusted upper band edge (high-band gamma^2 >= %.2f): **%.3f Hz**.\n\n", cohEdgeThresh, cohEdgeHz);
    else
        fprintf(fid, "High-band coherence never reaches %.2f in band.\n\n", cohEdgeThresh);
    end

    fprintf(fid, "## Nominal low-band FOPD\n\n");
    fprintf(fid, "| Param | Nominal | 95%% CI (bootstrap, n=%d) |\n|---|---:|---:|\n", nBootOk);
    fprintf(fid, "| K (rad/us) | %.6g | %.6g - %.6g |\n", lowModel.K, ci.K_p2p5, ci.K_p97p5);
    fprintf(fid, "| tau (ms) | %.4g | %.4g - %.4g |\n", lowModel.tau1_s*1e3, ci.tau_p2p5*1e3, ci.tau_p97p5*1e3);
    fprintf(fid, "| delay (ms) | %.4g | %.4g - %.4g |\n\n", lowModel.delay_s*1e3, ci.delay_p2p5*1e3, ci.delay_p97p5*1e3);

    fprintf(fid, "## Merge decision\n\n");
    fprintf(fid, "High-band FRF tested against the low-band fit's 95%% bootstrap CI tube.\n\n");
    fprintf(fid, "| Region | Fraction inside tube | Threshold |\n|---|---:|---:|\n");
    fprintf(fid, "| Overlap (<= %.2f Hz, amplitude test) | %.0f%% | %.0f%% |\n", lowMaxF, 100*overlapFrac, 100*mergeOverlapThr);
    fprintf(fid, "| Extension (> %.2f Hz, rolloff test) | %.0f%% | %.0f%% |\n\n", lowMaxF, 100*extFrac, 100*mergeExtThr);

    if doMerge
        fprintf(fid, "**DECISION: MERGE.** Amplitude-dependence is negligible across the achievable\n");
        fprintf(fid, "amplitudes and the small-signal rolloff matches the low-band model's\n");
        fprintf(fid, "extrapolation, so the bands were refit jointly into one wide-band FOPD.\n\n");
        fprintf(fid, "### Final wide-band FOPD\n\n");
        fprintf(fid, "| Param | Value |\n|---|---:|\n");
        fprintf(fid, "| K (rad/us) | %.6g |\n", mergedModel.K);
        fprintf(fid, "| tau (ms) | %.4g |\n", mergedModel.tau1_s*1e3);
        fprintf(fid, "| delay (ms) | %.4g |\n\n", mergedModel.delay_s*1e3);
        fprintf(fid, "The previously *extrapolated* bandwidth above the corner is now **measured**.\n");
    else
        fprintf(fid, "**DECISION: SEPARATE.** The high band leaves the low-band CI tube, i.e. the\n");
        fprintf(fid, "amplitude-dependence is measurable. The low-band FOPD remains the nominal\n");
        fprintf(fid, "(operating-amplitude) model; the high-band deviation becomes a high-frequency\n");
        fprintf(fid, "multiplicative uncertainty W(f) for robust Stage 2 design.\n\n");
        fprintf(fid, "### High-frequency multiplicative uncertainty\n\n");
        fprintf(fid, "Relative deviation |G_emp / G_low - 1|: overlap max **%.2f**, extension max **%.2f**.\n", ...
            W.max_overlap, W.max_extension);
    end

    clear cleanup;
end
