function realization = sample_friction_realization(frictionOverbound, massKg)
%SAMPLE_FRICTION_REALIZATION Map the friction overbound artifact to tvr_sim.
%   The current Simulink friction block accepts an acceleration-equivalent
%   bound d_max plus a direction asymmetry factor. This function samples the
%   richer overbound artifact and projects it onto that interface.

    if nargin < 2 || isempty(massKg)
        massKg = 0.5;
    end

    if nargin < 1 || isempty(fieldnames(frictionOverbound))
        realization = fallbackRealization(massKg);
        return;
    end

    caseNames = ["low", "nominal", "high", "asymmetric_worst"];
    caseWeights = [0.15, 0.45, 0.30, 0.10];
    caseName = weightedPick(caseNames, caseWeights);
    dyn = frictionOverbound.dynamic.(caseName);

    bPos = dyn.positive_direction.b_Ns_per_m;
    bNeg = dyn.negative_direction.b_Ns_per_m;
    muPos = dyn.positive_direction.mu_N;
    muNeg = dyn.negative_direction.mu_N;

    spatialMax = 0.0;
    if isfield(frictionOverbound, "spatial") && ...
            isfield(frictionOverbound.spatial, "amplitude_abs_max_N")
        spatialMax = frictionOverbound.spatial.amplitude_abs_max_N;
    end
    [centers, widths, amplitudes] = sampleSpatialBumps(frictionOverbound);
    spatialForce = sum(abs(amplitudes));

    posForce = max(muPos + spatialForce, 0);
    negForce = max(muNeg + spatialForce, 0);
    meanForce = 0.5 * (posForce + negForce);
    asym = (posForce - negForce) / max(posForce + negForce, eps);

    stiction = frictionOverbound.stiction;
    realization = struct( ...
        "case_name", caseName, ...
        "mass_kg", massKg, ...
        "b_pos_Ns_per_m", bPos, ...
        "b_neg_Ns_per_m", bNeg, ...
        "mu_pos_N", muPos, ...
        "mu_neg_N", muNeg, ...
        "breakaway_low_N", stiction.breakaway_low_N, ...
        "breakaway_high_N", stiction.breakaway_high_N, ...
        "v_epsilon_mps", stiction.v_epsilon_mps, ...
        "spatial_centers_m", centers, ...
        "spatial_widths_m", widths, ...
        "spatial_amplitudes_N", amplitudes, ...
        "jitter_amp_N", 0.05, ...
        "d_max_mps2", meanForce / massKg, ...
        "asym", max(min(asym, 0.8), -0.8), ...
        "positive_force_N", posForce, ...
        "negative_force_N", negForce, ...
        "spatial_force_N", spatialForce);
end

function realization = fallbackRealization(massKg)
    realization = struct( ...
        "case_name", "fallback_default", ...
        "mass_kg", massKg, ...
        "b_pos_Ns_per_m", 0, ...
        "b_neg_Ns_per_m", 0, ...
        "mu_pos_N", 0.975, ...
        "mu_neg_N", 0.525, ...
        "breakaway_low_N", 0, ...
        "breakaway_high_N", 0, ...
        "v_epsilon_mps", 5e-3, ...
        "spatial_centers_m", zeros(5, 1), ...
        "spatial_widths_m", ones(5, 1), ...
        "spatial_amplitudes_N", zeros(5, 1), ...
        "jitter_amp_N", 0.05, ...
        "d_max_mps2", 1.5, ...
        "asym", 0.3, ...
        "positive_force_N", 0.975, ...
        "negative_force_N", 0.525, ...
        "spatial_force_N", 0.0);
end

function [centers, widths, amplitudes] = sampleSpatialBumps(frictionOverbound)
    if ~isfield(frictionOverbound, "spatial")
        centers = zeros(5, 1);
        widths = ones(5, 1);
        amplitudes = zeros(5, 1);
        return;
    end
    spatial = frictionOverbound.spatial;
    countRange = double(spatial.bump_count_range(:)');
    nBumps = randi([countRange(1), countRange(2)]);
    posRange = double(spatial.position_range_m(:)');
    widthRange = double(spatial.width_range_m(:)');
    ampMax = spatial.amplitude_abs_max_N;

    centers = zeros(5, 1);
    widths = ones(5, 1);
    amplitudes = zeros(5, 1);
    centers(1:nBumps) = posRange(1) + rand(nBumps, 1) * diff(posRange);
    widths(1:nBumps) = widthRange(1) + rand(nBumps, 1) * diff(widthRange);
    amplitudes(1:nBumps) = ampMax * rand(nBumps, 1);
end

function choice = weightedPick(values, weights)
    weights = weights(:) ./ sum(weights);
    edges = cumsum(weights);
    idx = find(rand() <= edges, 1, "first");
    choice = values(idx);
end
